import { useState } from "react";
import Brand from "../components/Brand";
import GraphExplorer from "../components/GraphExplorer";
import CopyButton from "../components/CopyButton";
import ImportReport from "./ImportReport";
import { example } from "./example";
import type { Report } from "./report";
import { checkOutcome, testSummary } from "./checkSummary";
import { revisionFromMarker, sourceUrl } from "./sourceUrl";
import { edgeKey } from "./graph";

const steps = ["Scan evidence", "Repair case", "Repair outcome", "Verification evidence"];
const introductions = [
  "Every repair starts with understanding the structure. Explore the captured dependencies and select a file to inspect its connections.",
  "A case gives a repair its boundaries: the rule, its evidence, the files involved, and the checks worth reviewing.",
  "Compare the recorded snapshots. The selected case can be resolved while other repository violations remain.",
  "Architecture comparison and real checks answer different questions. Inspect both before trusting a repair.",
];

export default function Demo() {
  const [imported, setImported] = useState<Report>();
  const [step, setStep] = useState(0);
  const [side, setSide] = useState<"before" | "after">("before");
  const [repository, setRepository] = useState("");
  const [beforeRevision, setBeforeRevision] = useState("");
  const [afterRevision, setAfterRevision] = useState("");
  const report = imported ?? example;
  const { before, after, packet, result, execution } = report;
  const snapshot = side === "after" && after ? after : before;
  const selectedIds = new Set(packet.violations.map(v => v.id));
  const unrelated = result.persistentViolations.filter(v => !selectedIds.has(v.id)).length;
  const beforeEdges = new Set(before.edges.map(e => edgeKey(e.from, e.to)));
  const afterEdges = after && new Set(after.edges.map(e => edgeKey(e.from, e.to)));
  const removed = afterEdges ? before.edges.filter(e => !afterEdges.has(edgeKey(e.from, e.to))) : [];
  const added = after ? after.edges.filter(e => !beforeEdges.has(edgeKey(e.from, e.to))) : [];
  const revision = side === "after" ? afterRevision || revisionFromMarker(after?.gitMarker) : beforeRevision || revisionFromMarker(before.gitMarker);
  const load = (next?: Report) => { setImported(next); setStep(0); setSide("before"); setRepository(""); setBeforeRevision(""); setAfterRevision(""); };
  const selectStep = (index: number) => { setStep(index); if (index < 2) setSide("before"); };
  const primaryFiles = packet.primaryFiles;
  const counts = [before.modules.length, before.edges.length, before.violations.length, before.incompleteResolutionCount];
  return <>
    <header className="site-header"><div className="container nav"><Brand /><nav><a href="#/">← Back to overview</a><a href="#install">Install for Bob ↗</a></nav></div></header>
    <main id="main" className="container demo-main">
      <div className="demo-heading"><div><span className="eyebrow">THE REPAIR, UNDER A MICROSCOPE</span><h1>Follow the evidence<span className="accent">.</span></h1><p>Explore the structure, the case, and the recorded outcome.</p></div><span className="pill evidence-label">{imported ? "Imported report" : "Recorded example"}</span></div>
      <div className="evidence-notice"><span className="notice-icon" aria-hidden="true">i</span><p>{imported ? "These are your recorded artifacts. Importing does not rerun verification." : "This is a recorded example, not a live scan or the current repository status. No commands run in this demo."}</p><button className="text-button" onClick={() => load()}>Show example</button></div>
      <nav className="step-tabs" aria-label="Demo steps">{steps.map((name, i) => <button key={name} aria-current={step === i ? "step" : undefined} onClick={() => selectStep(i)}><span>{String(i + 1).padStart(2, "0")}</span>{name}<span className="step-arrow" aria-hidden="true">↗</span></button>)}</nav>
      <section className="step-intro"><span className="eyebrow">STEP {String(step + 1).padStart(2, "0")} / 04</span><h2>{steps[step]}</h2><p>{introductions[step]}</p></section>
      {step === 0 && <><div className="metric-grid">{["Captured files", "Dependency edges", "Repository violations", "Unresolved imports"].map((name, i) => <div className="metric" key={name}><span>{name}</span><strong className={i === 2 ? "status-warn" : ""}>{counts[i]}</strong></div>)}</div>{before.scannerWarnings.length > 0 && <div className="warning-box"><h3>Coverage warnings</h3>{before.scannerWarnings.map((warning, i) => <p key={i}>{warning}</p>)}</div>}<p className="subtle">Scope: <code>{before.root}</code> · Scanner: {before.scannerVersion} · Snapshot marker: {before.gitMarker}</p></>}
      {step === 1 && <section className="case-panel"><div className="case-top"><span className="pill">{packet.caseId}</span><span className="status-warn">{packet.severity} / {packet.rule}</span></div><h3>{packet.title}</h3><p>{packet.ruleExplanation}</p><div className="case-columns"><div><h4>Selected evidence</h4>{packet.violations.map(v => <div className="violation-item" key={v.id}><strong>{v.rule}</strong><code>{v.from} → {v.to}</code><p>{v.evidence ?? "Inspect the dependency in the graph below."}</p></div>)}</div><div><h4>Relevant tests in the case packet</h4><ul className="file-list">{packet.relevantTests.map(file => <li key={file}><code>{file}</code></li>)}</ul><h4>Expected outcome</h4><p>{packet.expectedEndCondition}</p><p className="subtle">Packet commands are guidance. Full verification uses the repository’s approved policy.</p></div></div></section>}
      {step === 2 && <><div className="metric-grid"><div className="metric"><span>Selected violations resolved</span><strong className="status-good">{result.afterId ? result.resolvedViolations.length : "—"}</strong></div><div className="metric"><span>New violations</span><strong>{result.afterId ? result.newViolations.length : "—"}</strong></div><div className="metric"><span>Unrelated violations remaining</span><strong className="status-warn">{result.afterId ? unrelated : "—"}</strong></div><div className="metric"><span>Comparison</span><strong className="small-metric">{result.afterId ? "Recorded" : "Unavailable"}</strong></div></div>{after && <details className="evidence-details"><summary>Inspect dependency changes ({removed.length} removed · {added.length} added)</summary><p>Derived from the supplied snapshots. These are dependency changes, not a source-code diff.</p>{removed.map(edge => <p className="edge-change removed" key={edgeKey(edge.from, edge.to)}><span>− Removed</span><code>{edge.from} → {edge.to}</code></p>)}{added.map(edge => <p className="edge-change added" key={edgeKey(edge.from, edge.to)}><span>+ Added</span><code>{edge.from} → {edge.to}</code></p>)}{!removed.length && !added.length && <p>No dependency edges changed.</p>}</details>}</>}
      {step !== 3 && <section className="graph-panel"><div className="panel-heading"><div><h3>{step === 0 ? "Captured repository graph" : "Case-focused graph"}</h3><p>{snapshot.violations.length} repository-wide violations · {side} snapshot</p></div><div className="segmented"><button aria-pressed={side === "before"} onClick={() => setSide("before")}>Before</button><button disabled={!after} aria-pressed={side === "after"} onClick={() => setSide("after")}>After</button></div></div>{!after && <p role="note" className="warning-box">After graph unavailable: this report has no completed comparison. A diagnostic snapshot is not comparison evidence.</p>}<GraphExplorer key={`${imported ? "imported" : "example"}-${side}-${step}`} snapshot={snapshot} primaryFiles={primaryFiles} repositoryView={step === 0} linkFor={file => sourceUrl(repository, revision, file)} /></section>}
      {step === 3 && <section className="verification"><div className={`result-banner ${result.status}`}><span className="eyebrow">RECORDED VERIFICATION STATUS</span><h3>{result.status}</h3><p>{result.reason}</p>{unrelated > 0 && <p>{unrelated} unrelated baseline violation{unrelated === 1 ? " remains" : "s remain"}. The status applies to the selected case, not a clean repository.</p>}</div><div className="check-grid"><article className="check-card"><span className="eyebrow">TESTS</span><h3 className={result.testExitCode === 0 ? "status-good" : "status-warn"}>{testSummary(result, execution)}</h3><p>Recorded aggregate exit code: {result.testExitCode}</p></article><article className="check-card"><span className="eyebrow">TYPECHECKS</span><h3 className={result.typecheckExitCode === 0 ? "status-good" : "status-warn"}>{checkOutcome(result.typecheckExitCode)}</h3><p>Recorded aggregate exit code: {result.typecheckExitCode}</p></article></div><p className="subtle">Counts appear only for complete supported summaries. Passing counts never override a failed exit code.</p><details className="evidence-details"><summary>Recorded test commands and full output</summary><h4>Commands</h4><pre>{result.testCommand || "No test command recorded."}</pre><h4>Output</h4><pre>{result.testOutput || "No test output recorded."}</pre></details>{execution && <details className="evidence-details"><summary>Per-command execution details</summary>{([...execution.tests.map(run => ({ ...run, kind: "Test" })), ...execution.typechecks.map(run => ({ ...run, kind: "Typecheck" }))]).map((run, i) => <div key={i}><h4>{run.kind} · {run.exitCode === null ? "Not run" : checkOutcome(run.exitCode)}</h4><code>{run.command}</code><pre>{run.output || "No output recorded."}</pre></div>)}</details>}<div className="diff-columns">{([["Resolved", result.resolvedViolations], ["Persistent", result.persistentViolations], ["New", result.newViolations]] as const).map(([title, violations]) => <article key={title}><h4>{title} <span>{result.afterId ? violations.length : "—"}</span></h4>{!result.afterId ? <p>No completed comparison.</p> : violations.length ? violations.map(v => <div className="violation-item" key={v.id}><strong>{v.rule}</strong><code>{v.from} → {v.to}</code></div>) : <p>None recorded.</p>}</article>)}</div></section>}
      <details className="source-settings"><summary>Source link settings</summary><p>Snapshot labels such as baseline or post-repair are not commit SHAs. Supply your repository and revisions to enable source links in the file inspector. User-supplied revisions are not verified.</p><div className="settings-fields"><label>GitHub repository URL<input type="url" placeholder="https://github.com/owner/repository" value={repository} onChange={event => setRepository(event.target.value)} /></label><label>Before revision<input value={beforeRevision} placeholder={revisionFromMarker(before.gitMarker) || "Explicit revision required"} onChange={event => setBeforeRevision(event.target.value)} /></label><label>After revision<input value={afterRevision} placeholder={revisionFromMarker(after?.gitMarker) || "Explicit revision required"} onChange={event => setAfterRevision(event.target.value)} /></label></div><p className="subtle">Case file paths are always available locally:</p><ul className="file-list">{packet.primaryFiles.map(file => <li key={file}><code>{file}</code> <CopyButton text={file} label="Copy path" /></li>)}</ul></details>
      <div className="step-footer"><button className="button ghost" disabled={step === 0} onClick={() => selectStep(step - 1)}>← Previous</button><span>{step + 1} of {steps.length}</span>{step < 3 ? <button className="button primary" onClick={() => selectStep(step + 1)}>Next: {steps[step + 1]} →</button> : <a className="button primary" href="#install">Try it in Bob IDE ↗</a>}</div>
      <div className="import-panel"><ImportReport onImport={load} /></div>
    </main><footer className="container site-footer"><Brand /><span>Recorded evidence. Real context.</span><a href="#/">Back to overview</a></footer>
  </>;
}
