import CopyButton from "./CopyButton";
import Download from "./Download";

const install = "npm ci --include=dev --ignore-scripts\nnpm link --ignore-scripts\nnode scripts/install-bob-addon.js --global";
const prompt = "Use ArchPulse for a guided scan and repair of this workspace. Show the dependency graph in the IDE browser if available; otherwise give me the clickable browser link. Retrieve the first case, present a concrete repair plan, and wait for my approval before editing. After approval, repair that case and call verify_case using the preserved full baseline path. Show the actual test and typecheck results, remaining violations, and after-graph link. Explain any coverage or verification blockers without claiming success.";
function Command({ text }: { text: string }) {
  return <div className="command-block"><pre><code>{text}</code></pre><CopyButton text={text} label="Copy commands" /></div>;
}
export default function Install() {
  return <section id="install" className="install-section page-section">
    <div className="section-heading"><div><span className="eyebrow">BRING IT TO YOUR WORKSPACE</span><h2>Your project.<br />Your Bob. <span className="accent">Your evidence.</span></h2></div><p>The browser demo is just the introduction. Install ArchPulse once and use it across supported JavaScript and TypeScript projects.</p></div>
    <div className="install-layout"><aside className="install-card"><img className="install-logo" src={`${import.meta.env.BASE_URL}archpulse_logo.png`} alt="" width="1280" height="1280" /><span className="pill">LOCAL MCP ADD-ON</span><h3>Install in Bob IDE</h3><p>No ArchPulse configuration files need to be added to your application for an initial scan.</p><Download /><div className="requirements"><h4>Before you begin</h4><p>Bob IDE and Node.js 24.x with npm. Internet access is needed to install ArchPulse dependencies. Install your target project’s dependencies normally for complete resolution.</p><p>The archive contains source, not a standalone executable. Keep the extracted folder and its dependencies installed.</p></div></aside>
    <ol className="install-steps">
      <li><span className="step-index">01</span><div><h3>Download and extract</h3><p>Extract the archive into a permanent folder of your choice. If you download a RAR file, use a RAR-capable extractor such as 7-Zip or WinRAR. Open a terminal in the extracted folder containing <code>package.json</code>. These commands run in the ArchPulse package, not this website or your application.</p></div></li>
      <li><span className="step-index">02</span><div><h3>Install dependencies and connect Bob</h3><p>The download intentionally omits <code>node_modules</code>. The first command downloads the locked dependencies and recreates that folder; internet access is required. The second registers the short <code>archpulse</code> command for use from any project folder.</p><Command text={install} /><p>The installer adds ArchPulse to your user-level Bob MCP settings and installs its global skill. It preserves other MCP entries. Reopen your terminal if the new command is not yet available.</p></div></li>
      <li><span className="step-index">03</span><div><h3>Restart Bob and open your application</h3><p>In Bob’s MCP settings, enable <strong>Use MCP Servers</strong>. Find <strong>archpulse</strong> and check that <code>scan_repository</code>, <code>get_case</code>, and <code>verify_case</code> are available.</p><p>If your application already has an <code>archpulse</code> entry in <code>.bob/mcp.json</code>, it overrides the global entry. Remove or disable that entry only if you want to use the new global installation.</p></div></li>
      <li><span className="step-index">04</span><div><h3>Start a guided scan and repair</h3><blockquote>{prompt}</blockquote><CopyButton text={prompt} label="Copy Bob prompt" /><p>Approve Bob’s tool call. If Bob cannot identify your workspace, provide your application’s absolute path as <code>workspacePath</code>. For a complete repair run, approve your project’s checks below before starting. Scanning needs no command approval; no detected violations means there may be no repair cases.</p><p><strong>What happens next:</strong> graph and findings → repair plan → your approval → repair and verification → results and after graph. Bob should wait for your approval before changing code.</p><p>The graph link opens a local browser preview while ArchPulse’s MCP server is running. Display inside the IDE depends on Bob’s available browser tools. Keep the returned <code>graph.html</code> path to reopen it offline after the preview closes.</p></div></li>
    </ol></div>
    <details className="approval-panel"><summary>Ready to verify a repair? Approve your project’s checks first.</summary><p>Open a terminal in <strong>your application’s folder</strong> and run:</p><Command text="archpulse setup" /><p>On Windows, if PowerShell blocks the command’s script shim, use:</p><Command text="archpulse.cmd setup" /><p>Setup shows the proposed test and typecheck commands, their working directories, and package script definitions. Review them and answer <code>y</code> at <strong>Approve these commands for future verification? [y/N]</strong>. No proposal ID to copy, and setup does not execute the checks. Approval is stored outside your application.</p><p>After approval, ask Bob to capture a <strong>fresh baseline</strong> before making repairs. If you change the check policy, run setup again and capture another baseline. Both approved tests and typechecks are required for full verification. Missing checks do not prevent scanning or viewing the graph. Package scripts can run shell commands and modify project files when verification executes them.</p><details><summary>If the short command is unavailable</summary><p>From the installed <strong>ArchPulse folder</strong>, use the launcher directly. Replace <code>{"<ABSOLUTE_PROJECT_PATH>"}</code> with your application’s full path, keeping the quotes:</p><Command text={'node scripts/archpulse.js setup --repo "<ABSOLUTE_PROJECT_PATH>"'} /></details></details>
  </section>;
}
