import CopyButton from "./CopyButton";
import Download from "./Download";

const install = "npm ci --include=dev --ignore-scripts\nnode scripts/install-bob-addon.js --global";
const prompt = "Use ArchPulse to scan this JS/TS workspace with scan_repository. Explain any coverage warnings, save the baseline ID, and use get_case to show one repair case if available. Do not change application files.";
function Command({ text }: { text: string }) {
  return <div className="command-block"><pre><code>{text}</code></pre><CopyButton text={text} label="Copy commands" /></div>;
}
export default function Install() {
  return <section id="install" className="install-section page-section">
    <div className="section-heading"><div><span className="eyebrow">BRING IT TO YOUR WORKSPACE</span><h2>Your project.<br />Your Bob. <span className="accent">Your evidence.</span></h2></div><p>The browser demo is just the introduction. Install ArchPulse once and use it across supported JavaScript and TypeScript projects.</p></div>
    <div className="install-layout"><aside className="install-card"><img className="install-logo" src={`${import.meta.env.BASE_URL}archpulse_logo.png`} alt="" width="1280" height="1280" /><span className="pill">LOCAL MCP ADD-ON</span><h3>Install in Bob IDE</h3><p>No ArchPulse configuration files need to be added to your application for an initial scan.</p><Download /><div className="requirements"><h4>Before you begin</h4><p>Bob IDE and Node.js 24.x with npm. Internet access is needed to install ArchPulse dependencies. Install your target project’s dependencies normally for complete resolution.</p><p>The ZIP contains source, not a standalone executable. Keep the extracted folder and its dependencies installed.</p></div></aside>
    <ol className="install-steps">
      <li><span className="step-index">01</span><div><h3>Download and extract</h3><p>Extract the archive into a permanent folder of your choice. If you download a RAR file, use a RAR-capable extractor such as 7-Zip or WinRAR. Open a terminal in the extracted folder containing <code>package.json</code>. These commands run in the ArchPulse package, not this website or your application.</p></div></li>
      <li><span className="step-index">02</span><div><h3>Install dependencies and connect Bob</h3><p>The download intentionally omits <code>node_modules</code>. The first command downloads the locked dependencies and recreates that folder; run it before the Bob installer. Internet access is required for this step.</p><Command text={install} /><p>The installer adds ArchPulse to your user-level Bob MCP settings and installs its global skill. It preserves other MCP entries.</p></div></li>
      <li><span className="step-index">03</span><div><h3>Restart Bob and open your application</h3><p>In Bob’s MCP settings, enable <strong>Use MCP Servers</strong>. Find <strong>archpulse</strong> and check that <code>scan_repository</code>, <code>get_case</code>, and <code>verify_case</code> are available.</p><p>If your application already has an <code>archpulse</code> entry in <code>.bob/mcp.json</code>, it overrides the global entry. Remove or disable that entry only if you want to use the new global installation.</p></div></li>
      <li><span className="step-index">04</span><div><h3>Ask Bob for your first scan</h3><blockquote>{prompt}</blockquote><CopyButton text={prompt} label="Copy Bob prompt" /><p>Approve Bob’s tool call. If Bob cannot identify your workspace, provide its absolute path as <code>workspacePath</code>. No detected violations means there may be no repair cases.</p></div></li>
    </ol></div>
    <details className="approval-panel"><summary>Ready to verify a repair? Approve your project’s checks first.</summary><p>Scanning requires no command approval. Full verification runs real tests and typechecks, so review and approve the proposed commands once per project from the installed ArchPulse folder. Replace <code>{"<ABSOLUTE_PROJECT_PATH>"}</code> with the full path to your application folder on your own computer, keeping the quotes.</p><Command text={'npm run configure -- --repo "<ABSOLUTE_PROJECT_PATH>"'} /><p>Review the exact commands and working directories, then replace <code>YOUR_PROPOSAL_ID</code> with the proposal ID printed above:</p><Command text={'npm run configure -- --repo "<ABSOLUTE_PROJECT_PATH>" --approve "YOUR_PROPOSAL_ID"'} /><p>Ask Bob to capture a <strong>fresh baseline</strong>, retrieve a case, and propose a repair. After you approve the edit, ask Bob to call <code>verify_case</code> with that baseline and case ID. Missing approved tests or typechecks prevent full verification; scanning and architecture-only comparison remain available. Package scripts can run shell commands and modify project files.</p></details>
  </section>;
}
